behaviors: 
  MyAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1000000
      learning_rate: 0.0003
      lambd: 0.95
      epsilon: 0.2
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      use_lstm: false
      memory_size: 256
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.01
        gamma: 0.99
        encoding_size: 16
        learning_rate: 0.0003
    max_steps: 500000000
    
